### ISSUE TITLE
Make argocd namespace configurable

### ISSUE THREAD

**Issue by giepa** [a1tan/argocdsecretsynchronizer#3]
Hi @a1tan 

Currently the argocd namespace is hardcoded. In our use case we deploy argocd in a different namespace. It would be great if we could configure the namespace, for example:

```
apiVersion: synchronizer.a1tan/v1alpha1
kind: SecretSynchronizer
metadata:
  name: secretsynchronizer
spec:
  argocdNamespace: argocd-prod
```

I would be happy to contribute this feature.

Thanks
Gideon
